server:
  port: 8090
mode: debug
authSecret: woodywoodpecker

dataSource:
  dbType: mysql
  database:
    - order
    - bcp
    - user
  url: 100.5.16.35:3306
  username: root
  password: 123456
  conns:
    maxOpenConns: 50
    maxIdleConns: 50
    connMaxLifetime: 50
    connMaxIdleTime: 50

kafka:
  topic: ccg

logger:
  filename: ./logs/log.log
  level: DEBUG
  maxSize: 64
  maxBackups: 10
  maxAge: 7