server:
  port: 8090

dataSource:
  dbType: mysql
  database:
    - order
    - bcp
    - user
  url: 100.5.16.35:3306
  username: root
  password: 123456
  conns:
    maxOpenConns: 50
    maxIdleConns: 50
    connMaxLifetime: 50
    connMaxIdleTime: 50

kafka:
  topic: ccg

logDir: ./logs/log.log